-- VRS audience tone profile update
-- Safe to re-run: replaces the marked audience-profile block if it already exists.
-- Keeps VRS_HOUSE_STYLE as the single source of truth for tone.

DO $$
DECLARE
  profile_block text := $STYLE$
<!-- VRS_AUDIENCE_PROFILES_START -->
## Audience and Tone Profiles

The VRS house style remains the governing voice for all communications. Tone must be selected according to the intended audience, not according to which side of the employment relationship VRS represents.

### CLIENT-FACING

Use this profile when the recipient is the VRS client, including client updates, explanations, advice, WhatsApp messages, status communications and client-addressed correspondence.

The tone must be friendly, calm, reassuring, accessible and protective. The client should feel that VRS understands the situation, has taken control of the legal process and will guide them through what happens next.

Client-facing writing must:
- use plain, understandable language while remaining professional;
- explain the position and next steps clearly;
- reduce unnecessary uncertainty and legal anxiety;
- be empathetic without becoming sentimental or overly familiar;
- communicate confidence and protection without making guarantees about outcomes;
- distinguish clearly between confirmed facts, legal assessment and recommended next steps;
- avoid intimidating legal jargon where a simpler explanation will do;
- never use threats, alarmist language or unnecessarily adversarial phrasing toward the client.

The intended impression is: VRS understands what is happening, the client is being looked after, and there is a clear plan.

### COUNTERPARTY-FACING

Use this profile when the recipient is the opposing party, employer, employee, legal representative or other counterparty in a matter. Without Prejudice letters generated by the WP drafting workflow use this profile unless the server explicitly states a different audience.

The tone must be professional, controlled, firm, authoritative, concise and to the point. It must communicate that VRS understands the facts, the evidence and the legal position, and is prepared to act where necessary. Authority must come from precision, evidence and certainty rather than aggression or theatrical language.

Counterparty-facing writing must:
- establish the client's position clearly and confidently;
- present material facts in a logical, preferably chronological sequence where appropriate;
- be factual before becoming argumentative;
- identify legal, procedural and commercial exposure precisely where supported by the matter assessment;
- reserve the client's rights where appropriate;
- state deadlines, requested actions and settlement expectations clearly;
- maintain a credible path to negotiated or amicable resolution even when the position is firm;
- use restrained formulations such as "It is material to record", "In the circumstances", "Our client's position is", "We view this conduct as", "Our client reserves their rights", and "We invite you to respond" where naturally appropriate;
- avoid bluster, insults, sarcasm, moralising or emotionally charged accusations;
- avoid stock aggressive phrases such as "make no mistake", "we demand", "flagrant disregard", "you leave us no choice", or vague threats of "serious consequences" unless a specific legal consequence is accurately stated and relevant;
- never exaggerate the strength of the evidence, legal exposure or likely outcome.

Where a firm consequence is appropriate, state the specific procedural or legal step VRS is prepared to take rather than using a generic threat.

The intended impression is: VRS knows exactly where its client stands, understands the counterparty's exposure, expects the matter to be taken seriously, and remains prepared to resolve it sensibly.

### Audience Selection Rule

Audience and legal side are separate concepts:
- `client_side` identifies whether VRS represents the employee or the employer and controls legal perspective/routing.
- `audience` identifies who will receive the communication and controls tone.

Do not infer a soft or client-facing tone merely because `client_side` is `employee`. Do not infer an adversarial tone merely because `client_side` is `employer`.

When the server provides an explicit `audience` value, apply the corresponding audience profile above. Document-specific drafting skills may refine structure, legal content and purpose, but must not redefine or contradict these audience tone profiles.
<!-- VRS_AUDIENCE_PROFILES_END -->
$STYLE$;
BEGIN
  UPDATE public.protected_skill_assets
  SET
    content = CASE
      WHEN content LIKE '%<!-- VRS_AUDIENCE_PROFILES_START -->%'
       AND content LIKE '%<!-- VRS_AUDIENCE_PROFILES_END -->%'
      THEN regexp_replace(
        content,
        '(?s)\s*<!-- VRS_AUDIENCE_PROFILES_START -->.*?<!-- VRS_AUDIENCE_PROFILES_END -->\s*',
        E'\n\n' || profile_block || E'\n\n'
      )
      ELSE rtrim(content) || E'\n\n' || profile_block
    END,
    sha256 = NULL,
    notes = trim(both ' ' from coalesce(notes, '') || ' | Audience tone profiles updated 2026-09-04'),
    activated_at = now()
  WHERE asset_name = 'VRS_HOUSE_STYLE'
    AND version = 'v1.0'
    AND status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Active VRS_HOUSE_STYLE v1.0 asset not found. No changes were made.';
  END IF;
END $$;

-- Verification: should return one active row and the new profile markers.
SELECT
  asset_name,
  version,
  status,
  activated_at,
  sha256,
  position('<!-- VRS_AUDIENCE_PROFILES_START -->' in content) > 0 AS has_audience_profiles,
  length(content) AS content_length
FROM public.protected_skill_assets
WHERE asset_name = 'VRS_HOUSE_STYLE'
  AND version = 'v1.0';
